import "../globals.css";
import {Header} from "@/shared/components/shared";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main>
      <Header />
      {children}
      {modal}
    </main>
  );
}
